### ISSUE TITLE
(Juniper) - Error when in

### ISSUE THREAD

**Issue by BbrSofiane** [open-craft/xblock-eoc-journal#42]
I've installed and added the eoc-journal xblock on a native installation of juniper but when I insert the component into a course, I get the following errors in LMS and CMS.

![image](https://user-images.githubusercontent.com/13796098/107070670-8910a400-67db-11eb-80e7-f6bb00a6932a.png)

Is the current version of the block compatible with Juniper?

```
==> /edx/var/log/lms/edx.log <==
Feb  5 17:51:36 ip-172-31-17-166 [service_variant=lms][edx_rest_framework_extensions.auth.jwt.middleware][env:sandbox] INFO [ip-172-31-17-166  29977] [user None] [middleware.py:72] - ('The view BlocksInCourseView allows Jwt Authentication. The required permission class, NotJwtRestrictedApplication,', ' was automatically added.')
Feb  5 17:51:36 ip-172-31-17-166 [service_variant=lms][edx_rest_framework_extensions.auth.jwt.decoder][env:sandbox] ERROR [ip-172-31-17-166  29977] [user None] [decoder.py:158] - Token verification failed.
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/edx_rest_framework_extensions/auth/jwt/decoder.py", line 156, in _verify_jwt_signature
    _ = JWS().verify_compact(token, key_set)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/jwkest/jws.py", line 517, in verify_compact
    return self.verify_compact_verbose(jws, keys, allow_none, sigalg)['msg']
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/jwkest/jws.py", line 588, in verify_compact_verbose
    raise BadSignature()
jwkest.BadSignature
Feb  5 17:51:36 ip-172-31-17-166 [service_variant=lms][edx_rest_framework_extensions.auth.jwt.decoder][env:sandbox] ERROR [ip-172-31-17-166  29977] [user None] [decoder.py:158] - Token verification failed.
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/edx_rest_framework_extensions/auth/jwt/decoder.py", line 156, in _verify_jwt_signature
    _ = JWS().verify_compact(token, key_set)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/jwkest/jws.py", line 517, in verify_compact
    return self.verify_compact_verbose(jws, keys, allow_none, sigalg)['msg']
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/jwkest/jws.py", line 588, in verify_compact_verbose
    raise BadSignature()
jwkest.BadSignature

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/edx_rest_framework_extensions/auth/jwt/decoder.py", line 156, in _verify_jwt_signature
    _ = JWS().verify_compact(token, key_set)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/jwkest/jws.py", line 517, in verify_compact
    return self.verify_compact_verbose(jws, keys, allow_none, sigalg)['msg']
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/jwkest/jws.py", line 588, in verify_compact_verbose
    raise BadSignature()
jwkest.BadSignature
```

==> /edx/var/log/cms/edx.log <==
Feb  5 17:51:36 ip-172-31-17-166 [service_variant=cms][contentstore.views.preview][env:sandbox] WARNING [ip-172-31-17-166  6986] [user 12] [preview.py:329] - Unable to render author_view for <VerticalBlockWithMixins @6DDA hide_from_toc=False, children=[BlockUsageLocator(CourseLocator('DiceyTech', 'PG001', '2020_T1', None, None), 'eoc-journal', 'b13a3fc34471469f8c387d9e448e4841')], is_entrance_exam=False, matlab_api_key=None, static_asset_path='', show_correctness='always', chrome=None, use_latex_compiler=False, visible_to_staff_only=False, xqa_key=None, display_name='Unit', xml_attributes={}, user_partitions=[], tags=[], edxnotes=True, graceperiod=datetime.timedelta(0), start=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=tzlocal()), video_bumper={}, edxnotes_visibility=True, default_tab=None, self_paced=True, position=None, show_reset_button=False, video_auto_advance=False, in_entrance_exam=False, name=None, source_file=None, max_attempts=None, hide_after_due=False, giturl=None, showanswer='finished', course_edit_method='Studio', days_early_for_beta=None, video_speed_optimizations=True, parent=BlockUsageLocator(CourseLocator('DiceyTech', 'PG001', '2020_T1', None, None), 'sequential', '7c0d6d6d0ce941d8a3fc0bc6604f4d3b'), rerandomize='never', due=None, format=None, graded=False, group_access={}>
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 327, in get_preview_fragment
    fragment = module.render(preview_view, context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/xblock/core.py", line 202, in render
    return self.runtime.render(self, view, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1979, in render
    return self.__getattr__('render')(block, view_name, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1423, in render
    return super(MetricsMixin, self).render(block, view_name, context=context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/xblock/runtime.py", line 829, in render
    frag = view_fn(context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/vertical_block.py", line 138, in author_view
    self.render_children(context, fragment, can_reorder=True, can_add=True)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/studio_editable.py", line 29, in render_children
    rendered_child = child.render(StudioEditableModule.get_preview_view_name(child), context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/xblock/core.py", line 202, in render
    return self.runtime.render(self, view, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1979, in render
    return self.__getattr__('render')(block, view_name, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1423, in render
    return super(MetricsMixin, self).render(block, view_name, context=context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/xblock/runtime.py", line 829, in render
    frag = view_fn(context)
  File "/home/ubuntu/xblock-eoc-journal/eoc_journal/eoc_journal.py", line 231, in student_view
    context.update(self._get_user_state())
  File "/home/ubuntu/xblock-eoc-journal/eoc_journal/eoc_journal.py", line 206, in _get_user_state
    "answer_sections": self.list_user_pb_answers_by_section(),
  File "/home/ubuntu/xblock-eoc-journal/eoc_journal/eoc_journal.py", line 306, in list_user_pb_answers_by_section
    blocks = self.list_pb_answers()
  File "/home/ubuntu/xblock-eoc-journal/eoc_journal/eoc_journal.py", line 393, in list_pb_answers
    for section, subsection, unit, block in self._iter_pb_answers(response)
  File "/home/ubuntu/xblock-eoc-journal/eoc_journal/eoc_journal.py", line 384, in <listcomp>
    {
  File "/home/ubuntu/xblock-eoc-journal/eoc_journal/eoc_journal.py", line 356, in _iter_pb_answers
    blocks = response['blocks']
KeyError: 'blocks'

**Comment by shimulch** [comment]
@BbrSofiane, Thanks for reporting the issue. This xblock is only known to work till `Ginkgo`. We are yet to find out its compatibility with `Juniper` and later releases.
